### PR TITLE
Added 2 phrases for Bubbe

### PR DESCRIPTION
**Pull request by jfrappier**
IDK if its any good, if you like them it will write some more.

### CODE REVIEW

**Comment by mbbroberg** [comment]
This is great @jfrappier! It does have a conflict right now because I merged #1. What's cool though is you can resolve it from the GUI now! We could even record it... #Commitmas 

screen shot 2016-12-24 at 10 58 49 am

**Comment by jfrappier** [comment]
Got time now?

**Comment by mbbroberg** [comment]
I do!

**Review by mbbroberg — APPROVED** [review]
LGTM

**Pull request merged**
